### ISSUE TITLE
Set up Packagist hook for auto-updates

### ISSUE THREAD

**Issue by danemacmillan** [linusshops/pipeline#1]

**Comment by waterloomatt** [comment]
This is complete. I created a GitHub webhook that will update Packagist on the `push` event for the master branch. 

1. Webhook for pipeline repository: https://github.com/linusshops/pipeline/settings/hooks/426674943
1. Packagist repo: https://packagist.org/packages/linusshops/pipeline

![Image](https://github.com/linusshops/pipeline/assets/1981303/354fa5d3-04ca-4093-a294-86bed580a61a)


![Image](https://github.com/linusshops/pipeline/assets/1981303/4a40f3a9-1fc1-4f5a-b51d-81d45a0774f4)

**Comment by danemacmillan** [comment]
Nice. Closing.
